name: flutter_advanced_courese
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # state_management:
  flutter_bloc: ^9.1.1
  # code genration:
  freezed: ^3.2.0
  # code generation:
  build_runner: ^2.3.3
  # json serialization:
  json_serializable: ^6.7.1
  # Classes and helper functions that support JSON code generation via the `json_serializable` package. 
  json_annotation: ^4.9.0
  # Annotations for the freezed code-generator. This package does nothing without freezed too.
  freezed_annotation: ^3.1.0
  #dependency injection:
  get_it: ^8.0.3
  # networking:
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.6.0
  dio: ^5.2.0
  retrofit_generator: ^10.0.0
  #locaization:
  intl: ^0.20.2
  easy_localization: ^3.0.7+1
  flutter_native_splash: ^2.4.6
  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.2.0
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.3
  firebase_core: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/svgs/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # see https://flutter.dev/to/font-from-package
